### ISSUE TITLE
crash with new version

### ISSUE THREAD

**Issue by Hypsellis** [GoryMoon/MoarSigns#31]
I get this crash on the new version. http://pastebin.com/64Xfk2MX

**Comment by zISKo666** [comment]
same here

**Comment by GoryMoon** [comment]
Doesn't look like an error on my side, have been testing some and it seem to be Optifine that is causing a similar crash, try removing  optifine.

**Comment by zISKo666** [comment]
well, no optifine im my pack but still crashing ... with 4.1.0.5 everything is fine
[crash-2017-01-09_22.12.14-client.txt](https://github.com/GoryMoon/MoarSigns/files/699311/crash-2017-01-09_22.12.14-client.txt)

**Comment by GoryMoon** [comment]
what pack are you using so I can easily test with the mods in that?

**Comment by zISKo666** [comment]
It's a self made pack that i created with MultiMC.
If i can help let me know how.

**Comment by GoryMoon** [comment]
I have identified that when both "MoarSigns" and "The One Probe" is installed it is crashing.
Installed separate, it works.

I will look into this some more, just wanted to let you know my findings.

**Comment by zISKo666** [comment]
Thank you for your fast response.

**Comment by GoryMoon** [comment]
ok, I have solved the issue now, will release a fix soon, it was a load order error with "The One Probe"(TOP), now the mod forces forge to load it before.
Simple fix but hard to see what was wrong from that stacktrace, it worked in the dev environment because it loaded it automatically before all the time, had to use both mods as standalone mods in another dev environment and then carefully look at the data when it crashed to see that it couldn't find a class from  TOP, therefor concluding that it was loading before TOP.
